src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: 'email', message: "Cet email est déjà utilisé.")]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\NotBlank(message: "Veuillez renseigner une adresse mail.")]
    #[Assert\Email(message: "Veuillez renseigner une adresse mail valide.")]
    private ?string $email = null;
    
    #[ORM\Column]
    private array $roles = [];
    
    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Assert\Regex(
        pattern: '/^[a-zA-Z0-9!@#$%^&*(),.?:{}|]*$/',
        message: 'Le champ peut contenir des lettres majuscules, minuscules, chiffres et certains symboles.'
        )] 
        #[Assert\NotBlank(message: "Veuillez renseigner un mot de passe.")]
        #[Assert\Length(min: 5, minMessage:" Le mot de passe doit faire plus de 5 caracteres.")]
        private ?string $password = null;
        
        #[ORM\Column(length: 255)]
        #[Assert\NotBlank(message: "Veuillez renseigner votre prénom.")]
        private ?string $firstname = null;
        
        #[ORM\Column(length: 255)]
        #[Assert\NotBlank(message: "Veuillez renseigner votr nom.")]
        private ?string $lastname = null;
        
        #[ORM\Column(type: Types::DATE_MUTABLE)]
        private ?\DateTimeInterface $birthdate = null;

        #[ORM\Column]
        private ?\DateTimeImmutable $createdAt = null;
        
        #[ORM\OneToMany(mappedBy: 'author', targetEntity: AdressUser::class)]
        private Collection $AdressUsers;
        
        #[ORM\Column(nullable: true)]
        private ?\DateTimeImmutable $updatedAt = null;
        
        #[ORM\Column()]
        #[Assert\NotBlank(message: "Veuillez accepter les condition.")]
        private ?bool $condition_user = null;

        #[ORM\OneToMany(mappedBy: 'user', targetEntity: Like::class, orphanRemoval: true)]
        private Collection $likes;


   

    public function __toString(): string
    {
        return $this->getFullname(); 
    }

    public function __construct()
    {
        $this->roles = ['ROLE_USER'];
        $this->createdAt = new \DateTimeImmutable();
        $this->AdressUsers = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFullname() : string {
        return $this->firstname . ' ' .$this->lastname;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection<int, DescriptionUser>
     */
    public function getAdressUsers(): Collection
    {
        return $this->AdressUsers;
    }

    public function addAdressUser(AdressUser $AdressUser): static
    {
        if (!$this->AdressUsers->contains($AdressUser)) {
            $this->AdressUsers->add($AdressUser);
            $AdressUser->setAuthor($this);
        }

        return $this;
    }

    public function removeAdressUser(AdressUser $AdressUser): static
    {
        if ($this->AdressUsers->removeElement($AdressUser)) {
            // set the owning side to null (unless already changed)
            if ($AdressUser->getAuthor() === $this) {
                $AdressUser->setAuthor(null);
            }
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getConditionUser(): ?bool
    {
        return $this->condition_user;
    }

    public function setConditionUser(?bool $condition_user): static
    {
        $this->condition_user = $condition_user;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birthdate;
    }

    public function setBirthDate(\DateTimeInterface $birthdate): static
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    /**
     * @return Collection<int, Like>
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): static
    {
        if (!$this->likes->contains($like)) {
            $this->likes->add($like);
            $like->setUser($this);
        }

        return $this;
    }

    public function removeLike(Like $like): static
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getUser() === $this) {
                $like->setUser(null);
            }
        }

        return $this;
    }

    


    
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('lastname',TextType::class,[
                'label' => 'Nom'
            ])
            ->add('firstname',TextType::class,[
                'label' => 'Prénom'
            ])
            ->add('email', EmailType::class,[
                'label' => 'Adress Email :'
            ])
            ->add('password', PasswordType::class,[
                'label' => 'Mot de passe'
            ])
            ->add('birthdate', DateType::class,[
                'label' => 'Date de Naissance'
            ])
            ->add('condition_user', CheckboxType::class,[
                
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
            
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use DateTimeImmutable;
use App\Entity\AdressUser;
use App\Form\AdressUserType;
use App\Repository\AdressUserRepository;
use App\Repository\LikeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class UserController extends AbstractController
{

// information de l'utilisateur 
    #[Route('/user', name: 'user')]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function user(
        Request $request,
        EntityManagerInterface $em
    ): Response {
        /**
         * @var User
         */
        $user = $this->getUser();

        $userForm = $this->createForm(UserType::class, $user);
        $userForm->remove('password')
            ->remove('condition_user');

        $userForm->handleRequest($request);
        if ($userForm->isSubmitted() && $userForm->isValid()) {

            $em->flush();
        }

        return $this->render('user/index.html.twig', [
            'form' => $userForm->createView()
        ]);
    }

// adress de l'utilisateurs
    #[Route('/user/adress', name: 'user_adress')]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function user_adress(
        AdressUserRepository $AdressUserRepository,
        UserInterface $currentUser
    ): Response {

        $adress = $AdressUserRepository->findUserAdress($currentUser);

        return $this->render('user/user_adress.html.twig', [
            'adresss' => $adress,
        ]);
    }

    // ajouter une adress
    #[Route('/user/add_adress', name: 'user_add_adress')]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function add_user_adress(
        Request $request,
        EntityManagerInterface $em,
        UserInterface $user,
        AdressUserRepository $AdressUserRepository,
        UserInterface $currentUser,
    ): Response {

        $newAdresss = new AdressUser();

        $addAdressForm = $this->createForm(AdressUserType::class, $newAdresss);


        $addAdressForm->handleRequest($request);

        if ($addAdressForm->isSubmitted() && $addAdressForm->isValid()) {

            $newAdresss->setAuthor($user);


            $em->persist($newAdresss);
            $em->flush();

            return $this->redirectToRoute('user_adress');
        }

        $adress = $AdressUserRepository->findUserAdress($currentUser);

        return $this->render('user/add_user_adress.html.twig', [
            'form' => $addAdressForm->createView(),
            'adresss' => $adress,
        ]);
    }

    // suprimer une adress
    #[Route('/user/remove_adress/{id}', name: 'remove_adress')]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function removeFriend(
        int $id,
        Request $request,
        AdressUserRepository $AdressUserRepository,
        EntityManagerInterface $em
    ): Response {
        $currentUser = $this->getUser();

        if (!$currentUser) {
            return $this->redirect($request->getUri());
        }

        $adress = $AdressUserRepository->find($id);

        if ($adress) {
            $em->remove($adress);
            $em->flush();
        }
        $referer = $request->server->get('HTTP_REFERER');
        return $referer ? $this->redirect($referer) : $this->redirect(('user'));
    }

    // modifier une adress
    #[Route('/user/edit_adress/{id}', name: 'edit_adress')]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function editDescription(
        int $id,
        Request $request,
        EntityManagerInterface $em,
        AdressUserRepository $AdressUserRepository
    ): Response {
        /**
         * @var User
         */
        $currentUser = $this->getUser();

        if (!$currentUser) {
            return $this->redirect($request->getUri());
        }

        $adress = $AdressUserRepository->find($id);

        $formAdress = $this->createForm(AdressUserType::class, $adress);

        $formAdress->handleRequest($request);
        if ($formAdress->isSubmitted() && $formAdress->isValid()) {

            $adress->setUpdatedAt(new DateTimeImmutable());

            $em->flush();

            return $this->redirectToRoute('user_adress');
        }
        $adress = $AdressUserRepository->findUserAdress($currentUser);

        return $this->render('user/updateDescription.html.twig', [
            'form' => $formAdress,
            'adresss' => $adress
        ]);
    }


// commande de l'utilisateur
    #[Route('/user/commande', name: 'user_commande')]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function user_commande(): Response
    {


        return $this->render('user/userCommande.html.twig', []);
    }

 // favoris utilisateurs
    #[Route('/user/like', name: 'user_favorite')]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function favorite(UserInterface $currentUser,
    LikeRepository $likeRepository): Response
    {

        $likes = $likeRepository->findUserLikes($currentUser);
        // dd($likes);

        return $this->render('user/userLikes.html.twig', [
            'likes' => $likes
        ]);
    }




    // changer le mot de passe
    #[Route('/user/change_password', name: 'changePassword')]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function changePassword(
        Request $request,
        EntityManagerInterface $em,
        UserPasswordHasherInterface $passwordHasher,
    ): Response {

        /**
         * @var User
         */
        $user = $this->getUser();

        $passwordForm = $this->createFormBuilder()
            ->add('newPassword', RepeatedType::class, [
                'type' => PasswordType::class,
                'constraints' => [
                    new NotBlank(['message' => 'Veuillez entrez deux mot de passe Identique']),
                    new Length([
                        'min' => 5,
                        'minMessage' => 'Veuillez entrez plus de 5 catactéres'
                    ])
                ],
                'invalid_message' => 'Les champs des mots de passe doivent correspondre.',
                'required' => false,
                'first_options'  => ['label' => 'Nouveau mot de passe'],
                'second_options' => ['label' => 'Confirmer le nouveau mot de passe'],
            ])
            ->getForm();

        $passwordForm->handleRequest($request);
        if ($passwordForm->isSubmitted() && $passwordForm->isValid()) {

            $newPassword = $passwordForm->get('newPassword')->getData();

            if ($newPassword) {
                $hash = $passwordHasher->hashPassword($user, $newPassword);
                $user->setPassword($hash);
            }

            $user->setUpdatedAt(new DateTimeImmutable());
            $em->flush();

            return $this->redirectToRoute('user');
        }
        return $this->render('user/changePassword.html.twig', [
            'form' => $passwordForm->createView(),
        ]);
    }
}

templates/user/add_user_adress.html.twig
{% extends 'base.html.twig' %}
{% block title %}Hello UserController!{% endblock%}
{% block body %}

<div class="user-body">
  {% include "includes/userMenu.html.twig" %}
  

  <div class="user-content">
    <div class="adress-content">
      <div class="add-new-adress">
        <div class="row-betwen">
          <div class="hiden"></div>
          <div class="user_name">
             <h2> {{ app.user.fullname }}</h2>
          </div>
          <div class="go-back">
            <a href="{{path('user_adress')}}">
              <img src="{{asset ('build/images/icons/circle-xmark-regular.svg')}}" alt="">
            </a>
          </div>
        </div>
        
        {{ form_start(form) }}
        {{ form_label(form.adress) }}
        {{ form_widget(form.adress) }}

        <div class="row-betwen">
          <div class="form-group-row">
            {{ form_label(form.city) }}
            {{ form_widget(form.city) }}
          </div>
          <div class="form-group-row">
            {{ form_label(form.postalCode) }}
            {{ form_widget(form.postalCode) }}
          </div>
      </div>

        {{ form_label(form.country) }}
        {{ form_widget(form.country) }}

        {{ form_label(form.phone) }}
        {{ form_widget(form.phone) }}

        {{ form_widget(form) }}
        <div class="button">
          <button class="btn btn-primary">Ajouter</button>
        </div>
        {{ form_end(form) }}
      </div>
    </div>
    <div class="adress-show">
      {% for adress in adresss %} {#
      {{ description.birthdate | format_datetime(pattern= 'd MM Y', locale='fr') }}
      <br />
      #}
      <div class="adress">
        <div class="remove-update-adress">
          <div class="update-adress">
            <a href="{{path('edit_adress', {'id': adress.id}) }}"><img src="{{asset ('build/images/icons/pen-to-square-regular.svg')}}" alt=""></a>
          </div>
          <div class=""></div>
          <div class="remove-adress">
            <a href="{{path('remove_adress', {'id': adress.id}) }}" class=""><img src="{{asset ('build/images/icons/circle-xmark-regular.svg')}}" alt=""></a>
          </div>
        </div>
        {{ app.user.fullname }} <br />
        {{ adress.adress }} <br />
        {{ adress.city }}, {{ adress.postalcode }} <br />
        {{ adress.country |country_name ('fr')}} <br />
        Numéros de téléphone : {{ adress.phone }}
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

templates/user/changePassword.html.twig
{% extends 'base.html.twig' %}
{% block title %}Hello UserController!{% endblock%}
{% block body %}

<div class="user-body">
  {% include "includes/userMenu.html.twig" %}

  <div class="user-form-content">
    <h2> {{ app.user.fullname }}</h2>
    <div class="flex-row">
      <div class="user-form">
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <div class="button">
          <button class="btn btn-primary">Modifier</button>
        </div>
        {{ form_end(form) }}

      </div>
    </div>
    
  </div>

 
      
  </div>
</div>
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Hello UserController!{% endblock%}
{% block body %}

<div class="user-body">
  {% include "includes/userMenu.html.twig" %}

  <div class="user-form-content">
    <h2> {{ app.user.fullname }}</h2>
    <div class="flex-row">
      <div class="user-form">
        {{ form_start(form) }}
        {{ form_label(form.email) }}
        {{ form_widget(form.email) }}
        <div class="row-betwen">
          <div class="form-group-row">
            {{ form_label(form.firstname) }}
            {{ form_widget(form.firstname) }}
          </div>
          <div class="form-group-row">
            {{ form_label(form.lastname) }}
            {{ form_widget(form.lastname) }}
          </div>
        </div>
        {{ form_label(form.birthdate) }}
        {{ form_widget(form.birthdate) }}
        <div class="button">
          <button class="btn btn-primary">Modifier</button>
        </div>
        {{ form_end(form) }}
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/user/updateDescription.html.twig
{% extends 'base.html.twig' %}
{% block title %}Hello UserController!{% endblock%}
{% block body %}

<div class="user-body">
  {% include "includes/userMenu.html.twig" %}


  <div class="user-content">
    <div class="adress-content">
      <div class="add-new-adress">
        <div class="row-betwen">
          <div class="hiden"></div>
          <div class="user_name">
             <h2> {{ app.user.fullname }}</h2>
          </div>
          <div class="go-back">
            <a href="{{path('user_adress')}}">
              <img src="{{asset ('build/images/icons/circle-xmark-regular.svg')}}" alt="">
            </a>
          </div>
        </div>
        
        {{ form_start(form) }}
        {{ form_label(form.adress) }}
        {{ form_widget(form.adress) }}

        <div class="row-betwen">
          <div class="form-group-row">
            {{ form_label(form.city) }}
            {{ form_widget(form.city) }}
          </div>
          <div class="form-group-row">
            {{ form_label(form.postalCode) }}
            {{ form_widget(form.postalCode) }}
          </div>
      </div>

        {{ form_label(form.country) }}
        {{ form_widget(form.country) }}

        {{ form_label(form.phone) }}
        {{ form_widget(form.phone) }}

        {{ form_widget(form) }}
        <div class="button">
          <button class="btn btn-primary">Modifier</button>
        </div>
        {{ form_end(form) }}
      </div>
    </div>
    <div class="adress-show">
      {% for adress in adresss %} {#
      {{ description.birthdate | format_datetime(pattern= 'd MM Y', locale='fr') }}
      <br />
      #}
      <div class="adress">
        <div class="remove-update-adress">
          <div class="update-adress">
            <a href="{{path('edit_adress', {'id': adress.id}) }}"><img src="{{asset ('build/images/icons/pen-to-square-regular.svg')}}" alt=""></a>
          </div>
          <div class=""></div>
          <div class="remove-adress">
            <a href="{{path('remove_adress', {'id': adress.id}) }}" class=""><img src="{{asset ('build/images/icons/circle-xmark-regular.svg')}}" alt=""></a>
          </div>
        </div>
        {{ app.user.fullname }} <br />
        {{ adress.adress }} <br />
        {{ adress.city }}, {{ adress.postalcode }} <br />
        {{ adress.country |country_name ('fr')}} <br />
        Numéros de téléphone : {{ adress.phone }}
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

templates/user/user.html.twig
{% extends 'base.html.twig' %}
{% block title %}Hello UserController!{% endblock%}
{% block body %}

<div class="user-body">
  <div class="user-menu">
    <nav></nav>
  </div>

  <div class="user-content">
    <div class="adress-content">
      <div class="add-new-adress">
        <div class="add">
          <img src="{{asset ('build/images/icons/plus-solid.svg')}}" alt="">
        </div>
        <h3>Ajouter une adresse</h3>
      </div>
      <div class="modal-content">

        {% if form is defined %}
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn btn-primary">Ajouter</button>
        {{ form_end(form) }}
    {% endif %}

      </div>

    </div>
    <div class="adress-show">
      {% for description in descriptions %} {#
      {{ description.birthdate | format_datetime(pattern= 'd MM Y', locale='fr') }}
      <br />
      #}
      <div class="adress">
        <div class="remove-update-description">
          <div class="update-description">
            <a href="{{path('edit-description', {'id': description.id}) }}"><img src="{{asset ('build/images/icons/pen-to-square-regular.svg')}}" alt=""></a>
          </div>
          <div class=""></div>
          <div class="remove-description">
            <a href="{{path('remove-description', {'id': description.id}) }}" class=""><img src="{{asset ('build/images/icons/circle-xmark-regular.svg')}}" alt=""></a>
          </div>
        </div>
        {{ app.user.fullname }} <br />
        {{ description.adress }} <br />
        {{ description.city }}, {{ description.postalcode }} <br />
        {{ description.country }} <br />
        Numéros de téléphone : {{ description.phone }}
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

templates/user/userLikes.html.twig
{% extends 'base.html.twig' %}
{% block title %}Hello UserController!{% endblock%}
{% block body %}

<div class="user-body">
    {% include "includes/userMenu.html.twig" %}


    <div class="user-content">
        <div class="product-cart">
            {% for like in likes %}
            {# Assuming 'like.product' is the associated product #}
            {% set product = like.product %}
            <div class="cart">
                {# <a href="{{ path('product_show', {id: product.id }) }}"> #}


                    <div class="product-img">
                        {% for loopIndex, image in product.images %}
                        <img src="{{ asset('uploads/products/' ~ image.name) }}" {% if loopIndex> 0 %}style="display:
                        none;"{% endif %} />
                        {% endfor %}
                    </div>
                    <div class="product-description">
                        <ul>
                            <li>{{ product.name }}</li>
                            <li>{{ (product.price / 100) | number_format(2, ', ' ) }} € </li>
                        </ul>
                    </div>

                {# </a> #}
            </div>
            {% endfor %}
        </div>
    </div>

</div>
{% endblock %}

templates/user/user_adress.html.twig
{% extends 'base.html.twig' %}
{% block title %}Hello UserController!{% endblock%}
{% block body %}

<div class="user-body">
  {% include "includes/userMenu.html.twig" %}


  <div class="user-content">
    <div class="adress-content">
      <div class="add-new-adress">
        <a href="{{path('user_add_adress')}}">
        <div class="add">
          <img src="{{asset ('build/images/icons/plus-solid.svg')}}" alt="">
        </div>
        <h3>Ajouter une adresse</h3>
      </a>
      </div>
    </div>
    <div class="adress-show">
      {% for adress in adresss %} {#
      {{ description.birthdate | format_datetime(pattern= 'd MM Y', locale='fr') }}
      <br />
      #}
      <div class="adress">
        <div class="remove-update-adress">
          <div class="update-adress">
            <a href="{{path('edit_adress', {'id': adress.id}) }}"><img src="{{asset ('build/images/icons/pen-to-square-regular.svg')}}" alt=""></a>
          </div>
          <div class=""></div>
          <div class="remove-adress">
            <a href="{{path('remove_adress', {'id': adress.id}) }}" class=""><img src="{{asset ('build/images/icons/circle-xmark-regular.svg')}}" alt=""></a>
          </div>
        </div>
        {{ app.user.fullname }} <br />
        {{ adress.adress }} <br />
        {{ adress.city }}, {{ adress.postalcode }} <br />
        {{ adress.country |country_name ('fr') }} <br />
        Numéros de téléphone : {{ adress.phone }}
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}